### ISSUE TITLE
Notebook: Lisa and Nyketha 

### ISSUE THREAD

**Issue by Nykke** [ga-wdi-exercises/mean-lab#105]
link to repo: https://github.com/laburr27/lab-notebook

Confidence: 3.0 
Completeness: 75% give or take

Comments: Technically we did a FULL CRUD HOWEVER! We keep getting a 500 error whenever we click the submit button for the "new" and "update" function and a 404 error for the "delete" function. Some guidance on how to fix this issue would be greatly appreciated. We didn't use handlebars, not sure what Angular's hangup is about form submission.

**Comment by superbuggy** [comment]
👍  500 was probably a mongoose error
