### ISSUE TITLE
Julia, Joe, Thai-Sun, Denzel 

### ISSUE THREAD

**Issue by JuliaNajafi** [ga-wdi-exercises/mean-lab#45]
https://github.com/JuliaNajafi/encoder

we had a lot of trouble with figuring out how to use user input, encode it, and save it to the database.. would we use a separate file? if so where do run that function to encode the message

**Comment by jshawl** [comment]
@JuliaNajafi you can put that logic right here - https://github.com/JuliaNajafi/encoder/blob/7bcf04f0b2e24a9381ea2c631026a0cc809704b2/index.js#L30-L31

Let me know if you'd like to pair on that!

👍
