### ISSUE TITLE
lab submission

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/mean-lab#53]
Repo: https://github.com/tedwards1884/KittyBoard
Deployed App: https://kittyboard.herokuapp.com/#/kittysats

Comments:

Didn't get the chance to finish full CRUD, but I've got index and new/create working. Was able to couple front- and back-end, which was cool. More importantly, I went slow enough to understand what I was doing as I was doing it - I feel much more confident this week than I have for the last two weeks, even though I didn't finish this lab. Deployment was a pain though.

**Comment by andrewsunglaekim** [comment]
👍
