### ISSUE TITLE
Dani lab

### ISSUE THREAD

**Issue by danielanoir** [ga-wdi-exercises/mean-lab#54]
comfort: 1
completeness 3

I kept redoing different apps to try to understand. I learned some stuff but I still can't get MEAN to work. 

This is my MEAN app but it has no crud functionality: 
repo: https://github.com/danielanoir/myface

This is the first app I was working on. It has full crud but I couldn't figure out how to put angular on top of it: 
repo: https://github.com/danielanoir/meangirls

**Comment by superbuggy** [comment]
👍 effort: i would just follow robin's screencast until i got it, honestly
