### ISSUE TITLE
Mean Lab 08/31/16

### ISSUE THREAD

**Issue by ahmedelk91** [ga-wdi-exercises/mean-lab#55]
Link to the repo: https://github.com/ahmedelk91/mean-task

Link to deployed app: https://mean-task.herokuapp.com/

Comfort: 1

Completeness: 2 

Comments: Had to redo this lab 3 times. Got CRUD on first attempt, but was unable to mount Angular. Tried to start with Angular on 2nd and 3rd attempt but was unable to render tasks on index and was stuck on that particular issue for hours with no error in the console. Will definitely have to get more and more reps in with the MEAN stack. I definitely want to get better at MEAN, but for now, I will have to take a slower approach to fully comprehend everything.

**Comment by superbuggy** [comment]
slower road is fine. I'd check out Robin's screencast repeatedly. 👍 overall
