### ISSUE TITLE
critique me: app for critiquing projects

### ISSUE THREAD

**Issue by megancoyle** [ga-wdi-exercises/mean-lab#57]
Repo: https://github.com/megancoyle/critique-me

Comfort: 3
Completeness: 4

Overall, I find myself constantly getting confused by Angular. Express made sense to me, but once Angular was thrown in the mix, I was at a loss. I'm going to try to review more tutorials to build simple apps over the weekend, although this has definitely been a struggle for me. Up next, I want to figure out how to delete comments.

**Comment by andrewsunglaekim** [comment]
keep at it! its tough! front end frameworks are tricky 👍
