### ISSUE TITLE
winston and Sarah's hw

### ISSUE THREAD

**Issue by zorba-strange** [ga-wdi-exercises/mean-lab#69]
https://github.com/zorba-strange/mad-gab2https://github.com/zorba-strange/mad-gab2

CL_2
C_2
it took a long time to get the backend up and running. Then yesterday we spent forever trying to get angular to work on top so eventually we killed the original repo and then decoupled everything and put it up on a new repo.

**Comment by superbuggy** [comment]
👍 decoupling is a good pattern
