### ISSUE TITLE
Barrett Cope Submission

### ISSUE THREAD

**Issue by bcope** [ga-wdi-exercises/mean-lab#73]
Repo: https://github.com/merubin/mean-lab

Group Members - Mike Rubin, Barrett Cope

Completeness: 3
Index http request successfully sent from front end server to back end server and rendering
Comfort level: 3

**Comment by merubin** [comment]
Deployed URL's
Backend: https://smile-be.herokuapp.com/
Frontend:https://merubin.github.io/smile-fe/
